##装数字类型转换为字符串
num_str=str(11)
print(type(num_str),num_str)
flaot_str=str(11.345)
print(type(flaot_str),flaot_str)
#字符串转换为数字
num=int("11")
print(type(num),num)

num2=float("11.345")
print(type(num2),num2)
#错误！想要将字符串转换为数字，要求为字符串内容都是数字
#num3=int("张楚岚")
#print(type(num3),num3)
#整数3转浮点数
float_num=float(11)
print(type(float_num),float_num)
#浮点数转整数
int_num=int(11.345)
print(type(int_num),int_num)